/**
 * Converts MegaMUD's recorded loop paths into this client's loops.
 *
 * The conversion is `loopsFromMegaMud` (`src/main/world/megamudLoops.ts`),
 * the same one the Import button on a server's page runs: this only reads a
 * folder from disk and writes the shelf the client ships
 * (`resources/loops/megamud.yaml`) as YAML somebody can read and edit.
 *
 *   npm run build:loops [-- <mega-paramud/Default> <out.yaml>]
 */
import fs from 'node:fs';
import path from 'node:path';

import { WorldGraph } from '../src/main/world/WorldGraph.ts';
import { RealmLibrary } from '../src/main/world/RealmLibrary.ts';
import { loopsFromMegaMud } from '../src/main/world/megamudLoops.ts';
import { megaMudLoops } from '../src/shared/megamudPaths.ts';

const source = process.argv[2] ?? path.resolve('mega-paramud/Default');
const out = process.argv[3] ?? path.resolve('resources/loops/megamud.yaml');
/*
 * The realm those paths were recorded against — not necessarily the one this
 * client ships. `mega-paramud` is Paradigm's, and replaying its paths through
 * stock GreaterMUD fits 7 loops out of 488: the room numbers are a different
 * realm's. Pass the database the paths belong to.
 */
const realm = process.argv[4] ?? '';

const world = realm
  ? new RealmLibrary({
      shippedDir: path.resolve('resources/world'),
      cacheDir: path.join(path.dirname(path.resolve('resources/config/user.yaml')), 'realms'),
      notify: (message) => console.log(`  ${message}`)
    }).load(realm).graph
  : WorldGraph.load(path.resolve('resources/world/paradigm.jsonl.gz'));
/*
 * Every file in the folder, as the Import button on a server's page hands
 * them over: the loops among them are found, and `Rooms.md` read, by the same
 * code (`megaMudLoops`), and converted by the same converter.
 */
const files = fs
  .readdirSync(source)
  .filter((name) => /\.mp$/i.test(name) || name.toLowerCase() === 'rooms.md')
  .sort()
  .map((name) => ({ name, text: fs.readFileSync(path.join(source, name), 'latin1') }));
const paths = megaMudLoops(files);
const { loops, dropped, numbered: collisions } = await loopsFromMegaMud(world, paths);

const quote = (text) => `'${text.replace(/'/g, "''")}'`;

const body = loops
  .map((loop) => {
    const stops = loop.stops.map((stop) => `      - ${quote(stop.room)}`).join('\n');
    return `  - name: ${quote(loop.name)}\n    stops:\n${stops}`;
  })
  .join('\n');

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(
  out,
  `# MegaMUD's loops, as waypoints.
#
# Generated by \`npm run build:loops\` from the recorded loops in
# mega-paramud/Default (a path whose start and end room are one, placed by
# Rooms.md where the folder has it): each loop's directions were replayed through
# the shipped realm data and reduced to the fewest places whose routes
# reproduce the same loop. Nothing here is a recorded step -- the client
# plans each leg itself, so a corridor that changes is picked up for free.
#
# Each is named the way whoever recorded it named it -- the title on the path
# file's own first line -- under the area MegaMUD filed it in. The room the
# loop starts from is its first stop, not its name: four paths that all begin
# at Narrow Ledge are East Half, West Half, Middle and Full Loop.
#
# ${loops.length} loops from ${paths.length} recorded loops.
# Dropped: ${dropped.start} whose starting room the realm data does not have,
# ${dropped.steps} whose steps do not fit it, ${dropped.short} too short to loop.
# ${collisions} share a label with an earlier one and carry a number: a name is
# how this client addresses a loop, so no two of them may be spelled the same.
#
# Copy one into \`automation.loops\` in your options file, or name it there.
loops:
${body}
`,
  'utf8'
);

console.log(
  `${loops.length} loops written to ${path.relative(process.cwd(), out)} ` +
    `(dropped ${dropped.start} start, ${dropped.steps} steps, ${dropped.short} short; ` +
    `${collisions} numbered to keep every name unique)`
);
const sizes = loops.map((loop) => loop.stops.length).sort((a, b) => a - b);
if (sizes.length > 0) {
  console.log(
    `  waypoints per loop: min ${sizes[0]}, median ${sizes[Math.floor(sizes.length / 2)]}, max ${sizes.at(-1)}`
  );
  console.log(`  e.g. ${loops[0].name}: ${loops[0].stops.map((stop) => stop.room).join(' -> ')}`);
}
